import React from 'react'
import '@/assets/styles/globals.css'
import { Metadata } from 'next'
import Navbar from '@/components/NavBar'

export const metadata: Metadata = {
  title: 'Property Pulse',
  description: 'learning nextjs 14',
}

const mainLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body>
        {/* commenting out for now, focusing on cookbook items */}
        {/* <Navbar /> */}
        <div className="h-screen flex flex-col place-content-between p-4">
          <div className="p-4">Header</div>
          <div className="p-4 flex-grow">{children}</div>
          <div className="p-4">Footer</div>
        </div>
      </body>
    </html>
  )
}

export default mainLayout

/**
 * 1. this file will always be generated by nextjs, even if you delete it
 * 2. this file with this exact name `layout.tsx|.js` the main root layout file is essential for nextjs
 * 3. It will accept children props and return the children wrapped in <html> and <body> tags
 */
